### ISSUE TITLE
✨ Discord presence support

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#102]
## Task
Implementing the support for discord presence
> see [Presence | Discord API](https://discord.com/developers/docs/topics/gateway#presence)

![image](https://user-images.githubusercontent.com/53050011/135734841-ee9b8936-89fd-44f2-9ae4-0847147b9f6d.png)

**Comment by xtanion** [comment]
By presence, Do you mean "discord rich presence?"

**Comment by Sigmanificient** [comment]
> By presence, Do you mean "discord rich presence?"

Firstly, just the normal presence with the acitivity type & the custom text. Then will might try to add rich presence too

**Comment by rexdivakar** [comment]
Hey @Sigmanificient  i can do this, please assign it to me

**Comment by rexdivakar** [comment]
Hey @Sigmanificient can you please elaborate at which event you want the discord presence activated ?

**Comment by Sigmanificient** [comment]
Since @rexdivakar delete his fork, that feature is left without anyone assigned to it, any person willing to try?

**Comment by Endercheif** [comment]
Does anyone want to take this issue?

**Comment by Lunarmagpie** [comment]
Go for it

**Comment by Lunarmagpie** [comment]
It would be a good idea to hold off on this until sharding is done imo. I believe each shard needs to have its presence set independently so that'll need to be accounted for.

**Comment by Lunarmagpie** [comment]
This is good to do again

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
