### ISSUE TITLE
🧪 Improving Code Coverage with new pytests

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#121]
As of right now, there is only 2, or more like a single test for the whole library.

# Tasks
Implement new pytests to validate the behavior of objects, utils and core components of the library.
All missing tests on current should be passed.

**Comment by gillesigot** [comment]
Hello, I just added [this PR](https://github.com/Pincer-org/Pincer/pull/169) to increase code coverage.
I'll try to add more if I have time.

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
