### ISSUE TITLE
Speech Recognizer using python

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Pincer-org/Pincer#125]
**Describe the solution you'd like**
I want to add speech recognizer code that can identify words that we spoke and this can be used for further improvement of any customized work.

**Comment by PradeepBaipadithaya** [comment]
Please assign me with this issue.

**Comment by Sigmanificient** [comment]
Hello @Pincer-org/pincer-core, I am not sure to really understand what you meant with this issue.
Pincer is a API wrapper for the discord API and as far as I know, this isn't the role of pincer to provide voice channel audio speech recognition.
Moreover, it seems that you are opening a similar issue within [an other repository](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/issues/195), so i really have a doubt on your understanding of our project.
