### ISSUE TITLE
✨ Allow users to decide default encoding for pillow images

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#131]
**Is your feature request related to a problem? Please describe.**
Pincer sends pillow images as PNGs by default. Bot developers with image heavy bots would benefit from being able to change the default image type and parameters to whatever they want.

**Describe the solution you'd like**
I think a config object in `pincer/utils/_config.py` is the best option right now. Im open to other suggestions ofc.

### Notes
The Config "thing" will have to handle all of the options for image.save(). [Theres a lot of stuff
](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html) and none of it is guaranteed to be used besides format. Have fun :) Luckily we only need to handle the ones that the [discord docs](https://discord.com/developers/docs/reference#image-formatting) mention. 
Also make sure the system can be expanded if we need other configuration ofc.

**Comment by Endercheif** [comment]
What if it’s just an argument in the Client constructor? 
`bot = Client(token=…, default_image_type=…)`

**Comment by Lunarmagpie** [comment]
tfw you accidentally hit close. I shouldn't be trusted.
Anyway, the problem with that is that the user needs to supply several kwargs cause you would probably specify compression, compression type, etc if you are doing that.
`bot = Client(token=…, default_image_param={DICT OF KWARGS})` could work.

**Comment by Lunarmagpie** [comment]
I was thinking maybe a similar idea with decorators. I do think that sperating config for every Bot object would be impossible/really hard to implement though so a global config object would be much easier.

```python
import Bot, config

@config.pillow_default(a=...,b=...)
class Client(Bot):
    ...

```

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
