### ISSUE TITLE
Change minimum version to 3.7 instead of 3.6

### ISSUE THREAD

**Issue by Endercheif** [Pincer-org/Pincer#16]
**Describe the bug**
Many packages and features do not support Python 3.6 anymore.
- `aiohttp` -> >= 3.7
- `typing.Protocol` >= 3.7
- `__future__.annotations` >= 3.7
- `dataclasses` >= 3.7

- `async` and `await` being reserved keywords >= 3.7
- `asyncio` is a lot faster from 3.6 to 3.7
- UTF-8 encoding is default (unless specified) - we wont need `# -*- coding: utf-8 -*`
- `__getattr__()` can be defined for classes

**To Reproduce**
Either run in Python 3.6 or set your IDE to Python 3.6.

**Solution**
Change the version to 3.7

**Comment by Arthurdw** [comment]
PR has been merged.

Thanks for contributing ♥
