### ISSUE TITLE
:rotating_light: Flake8 W503/W504 warnings

### ISSUE THREAD

**Issue by mwath** [Pincer-org/Pincer#164]
**Describe the bug**
Flake8 warns about both line break before and after a binary operator (W503 and W504).
Therefore you always have warnings no matter what code style you use.

**Expected behavior**
Flake8 should not warn about W503 errors since Pincer is already using W504's code style.

**Potential fix**
Add `W503` to the ignore list in the file `.flake8`.
e.g.
```INI
ignore =
    ...
    H501,
    # W503: line break before binary operator
    W503
```

**Screenshots**
![image](https://user-images.githubusercontent.com/64019721/138607869-16de2995-144c-4408-a9c5-9e40e1b072dc.png)
![image](https://user-images.githubusercontent.com/64019721/138607894-b2884702-3289-46f5-a138-00104466b55f.png)

**Comment by mjneff2** [comment]
I can take this one.
