### ISSUE TITLE
✨ Autocomplete type

### ISSUE THREAD

**Issue by Arthurdw** [Pincer-org/Pincer#183]
Create autocomplete type. Should function abt the same as choices.

https://discord.com/developers/docs/interactions/application-commands#autocomplete

**Comment by Lunarmagpie** [comment]
This should be done after #227

**Comment by beastmatser** [comment]
I made the code for this, most of the stuff was already added, I am waiting on #379 to be merged so that I can add it to the codebase.

**Comment by Lunarmagpie** [comment]
#379 is merged. you can open your PR now.

**Comment by Sigmanificient** [comment]
@beastmatser

**Comment by beastmatser** [comment]
I thought I did this, but I turns out I was missing some things and my code sort of disappeared, so I do not have it anymore
