### ISSUE TITLE
🚸 Make `MessageContext.ack()` flag argument optional

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#186]
Basically what the title says. I think the method would be a bit more readable if you didn't need an argument for interactions without flags.

**Comment by Arthurdw** [comment]
Yeah, this was a small mistake.

The only thing that has to change is the params and default to `None` since the `Interaction.ack` implements this too as optional.
_(https://github.com/Pincer-org/Pincer/blob/main/pincer/objects/app/interactions.py#L259)_

This should be an easy fix.

**Comment by Lunarmagpie** [comment]
Please assign this to me
