### ISSUE TITLE
✨ Add `raw_content` property to `UserMessage`

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#192]
This will remove text formatting (ex Italics, Bold, Code Blocks). This will ame it easier to deal with text.

**Comment by beastmatser** [comment]
I suppose I can take a look at this, do emoji's need to removed as well?

**Comment by Lunarmagpie** [comment]
I don't think so because I think it would be good if you can search for an emoji in a cleaned string

**Comment by beastmatser** [comment]
I think it should be called `clean_content`, because `raw_content` tells me nothing has changed to the content

**Comment by Lunarmagpie** [comment]
> I think it should be called `clean_content`, because `raw_content` tells me nothing has changed to the content

Sure! It'll make more sense for dpy devs too.

**Comment by lapin-b** [comment]
Just putting my grain of salt.

I personally wouldn't put the burden on cleaning the text -- removing the content aforementioned in the comment thread -- on the library but rather in something else, like user code. Okay, maybe if this comes often enough, why not make something external that is standalone.

I would rather have a property or a method that will nullify effects of certain mentions like `@everyone` or `@here`, replace different mentions[^1] by their textual counterpart. For example, `<#0123456789>` becomes `#my-channel-has-been-mentioned`.

If cleaning the message text will be useful at multiple places in the library, why not. If it is convenient for the end user so they don't have headaches with regex, also why not !

[^1]: Roles, channels, users, whatever is mentionable, you name it!

**Comment by beastmatser** [comment]
#237

**Comment by Sly-Little-Fox** [comment]
Should it also convert emojis like `:eyes:` to unicode?
