### ISSUE TITLE
Docs: FAQ for ``UserMessage`` vs ``Message``

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#199]
As someone who has been exposed to multiple python discord api wrappers, and even coming into this being able to use the docs well I found it difficult to discern the difference and required @Sigmanificient 's help to figure it out.

I think it would be great to add an FAQ section to the docs for things like this.

**Comment by Arthurdw** [comment]
Yeah, we probbably should have a FAQ somewhere. But for example this question is documented in the docs:  
  
Message: A discord message that **will be** send to discord  
UserMessage: Represents a message **sent in a channel** within Discord.

In other words, the Message object is something which the library uses to send messages and the UserMessage object is to receive messages.
