### ISSUE TITLE
Feature: The ability to send a message to someone

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#203]
**Is your feature request related to a problem? Please describe.**
I would like to send messages to ``User``'s

**Describe the solution you'd like**
``await User.send(message)``

**Describe alternatives you've considered**
Not being able to send messages.

**Comment by Lunarmagpie** [comment]
Please assign this to me

**Comment by Lunarmagpie** [comment]
Should also close #201 once implemented
