### ISSUE TITLE
Bug: ``Guild.ban(**kwargs)`` missing

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#216]
**Describe the bug**
We should be able to pass kwargs such as ban reason

**To Reproduce**
Try ban someone with a reason.

**Expected behavior**
It accepts the reason

**Comment by Arthurdw** [comment]
Should be implemented like how it has been done for the channels:  
https://github.com/Pincer-org/Pincer/blob/main/pincer/objects/guild/channel.py#L248-L275

**Comment by Lunarmagpie** [comment]
Please assign this to me
