### ISSUE TITLE
Adding Voice Recording And Transmitting

### ISSUE THREAD

**Issue by VincentRPS** [Pincer-org/Pincer#217]
ref: https://discord.com/developers/docs/resources/voice
ref2: https://github.com/Rapptz/discord.py/pull/6507

**Comment by Arthurdw** [comment]
I think we should first properly implement all text related communications _(commands, menus, ...)_
But this is definitly something which needs to be in the library.

**Comment by Lunarmagpie** [comment]
Closed in favor of #356
