### ISSUE TITLE
:bug: Fix broken command loading

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#221]
Commands will raise a Bad Request error when loading.
Breaks on [this commit.](https://github.com/Pincer-org/Pincer/commit/2d9becf0a588619744097fb79115478a3feaa40d)

**Comment by Sigmanificient** [comment]
This commit was intended to fix an issue with the conversion of `guild` object where the `fin_fac` try to convert `channel` objects to `list`. I used the `isdataclass` to avoid checking specifically for `Channel` or `APIObjects` and also avoid creating a circular import. That can be change to a more specific rule i believe to have both feature works as intended.
