### ISSUE TITLE
✨ Implement Guild Methods

### ISSUE THREAD

**Issue by Endercheif** [Pincer-org/Pincer#222]
Many of the guild methods are yet to be added. This issue will serve as a checklist for them. 
If you want to become a contributor, implementing a few of these is a good first issue. This issue will be divided up into parts. If you are working on some methods, comment on what you are doing so that you can be assigned to it and there would not be others doing the same thing.

**Comment by Endercheif** [comment]
- [ ] [Create Guild](https://discord.com/developers/docs/resources/guild#create-guild)
- [ ] [Get Guild](https://discord.com/developers/docs/resources/guild#get-guild)
- [ ] [Get Guild Preview](https://discord.com/developers/docs/resources/guild#get-guild-preview)
- [ ] [Modify Guild](https://discord.com/developers/docs/resources/guild#modify-guild)
- [ ] [Delete Guild](https://discord.com/developers/docs/resources/guild#delete-guild)
- [ ] [Get Guild Channels](https://discord.com/developers/docs/resources/guild#get-guild-channels)
- [ ] [Create Guild Channel](https://discord.com/developers/docs/resources/guild#create-guild-channel)
- [ ] [Modify Guild Channel Positions](https://discord.com/developers/docs/resources/guild#modify-guild-channel-positions)
- [ ] [List Active Threads](https://discord.com/developers/docs/resources/guild#list-active-threads)
- [ ] [Get Guild Member](https://discord.com/developers/docs/resources/guild#get-guild-member)
- [ ] [List Guild Members](https://discord.com/developers/docs/resources/guild#list-guild-members)
- [ ] [Search Guild Members](https://discord.com/developers/docs/resources/guild#search-guild-members)
- [ ] [Add Guild Member](https://discord.com/developers/docs/resources/guild#add-guild-member)
- [ ] [Modify Guild Member](https://discord.com/developers/docs/resources/guild#modify-guild-member)
- [ ] [Modify Current Member](https://discord.com/developers/docs/resources/guild#modify-current-member)
- [ ] [Modify Current User Nick](https://discord.com/developers/docs/resources/guild#modify-current-user-nick)
- [ ] [Add Guild Member Role](https://discord.com/developers/docs/resources/guild#add-guild-member-role)
- [ ] [Remove Guild Member Role](https://discord.com/developers/docs/resources/guild#remove-guild-member-role)
- [ ] [Remove Guild Member](https://discord.com/developers/docs/resources/guild#remove-guild-member)
- [ ] [Get Guild Bans](https://discord.com/developers/docs/resources/guild#get-guild-bans)
- [ ] [Get Guild Ban](https://discord.com/developers/docs/resources/guild#get-guild-ban)
- [ ] [Create Guild Ban](https://discord.com/developers/docs/resources/guild#create-guild-ban)
- [ ] [Remove Guild Ban](https://discord.com/developers/docs/resources/guild#remove-guild-ban)
- [ ] [Get Guild Roles](https://discord.com/developers/docs/resources/guild#get-guild-roles)
- [ ] [Create Guild Role](https://discord.com/developers/docs/resources/guild#create-guild-role)
- [ ] [Modify Guild Role Positions](https://discord.com/developers/docs/resources/guild#modify-guild-role-positions)
- [ ] [Modify Guild Role](https://discord.com/developers/docs/resources/guild#modify-guild-role)
- [ ] [Delete Guild Role](https://discord.com/developers/docs/resources/guild#delete-guild-role)
- [ ] [Get Guild Prune Count](https://discord.com/developers/docs/resources/guild#get-guild-prune-count)
- [ ] [Begin Guild Prune](https://discord.com/developers/docs/resources/guild#begin-guild-prune)
- [ ] [Get Guild Voice Regions](https://discord.com/developers/docs/resources/guild#get-guild-voice-regions)
- [ ] [Get Guild Invites](https://discord.com/developers/docs/resources/guild#get-guild-invites)
- [ ] [Get Guild Integrations](https://discord.com/developers/docs/resources/guild#get-guild-integrations)
- [ ] [Delete Guild Integration](https://discord.com/developers/docs/resources/guild#delete-guild-integration)
- [ ] [Get Guild Widget Settings](https://discord.com/developers/docs/resources/guild#get-guild-widget-settings)
- [ ] [Modify Guild Widget](https://discord.com/developers/docs/resources/guild#modify-guild-widget)
- [ ] [Get Guild Widget](https://discord.com/developers/docs/resources/guild#get-guild-widget)
- [ ] [Get Guild Vanity URL](https://discord.com/developers/docs/resources/guild#get-guild-vanity-url)
- [ ] [Get Guild Widget Image](https://discord.com/developers/docs/resources/guild#get-guild-widget-image)
- [ ] [Get Guild Welcome Screen](https://discord.com/developers/docs/resources/guild#get-guild-welcome-screen)
- [ ] [Modify Guild Welcome Screen](https://discord.com/developers/docs/resources/guild#modify-guild-welcome-screen)
- [ ] [Modify Current User Voice State](https://discord.com/developers/docs/resources/guild#modify-current-user-voice-state)
- [ ] [Modify User Voice State](https://discord.com/developers/docs/resources/guild#modify-user-voice-state)

**Comment by Sigmanificient** [comment]
Your are the best

**Comment by trag1c** [comment]
Taking `Create Guild`, `Get Guild`, `Get Guild Preview`, `Modify Guild`, `Delete Guild`

**Comment by Endercheif** [comment]
Taking `Create Guild Channel`, `Modify Guild Channel Positions`, `List Active Threads`, `List Guild Members`, `Search Guild Members`, and `Add Guild Member`

**Comment by Endercheif** [comment]
taking  `Modify Current Member`, `Modify Current User Nick`, `Add Guild Member Role`, `Remove Guild Member Role` and `Remove Guild Member`

**Comment by trag1c** [comment]
Taking `Get Guild Roles`, `Create Guild Role`, `Modify Guild Role Positions`, `Modify Guild Role`, and `Delete Guild Role`

**Comment by trag1c** [comment]
Taking `Get Guild Prune Count`, `Begin Guild Prune`, `Get Guild Voice Regions`, `Get Guild Invites`, and `Get Guild Integrations`
