### ISSUE TITLE
💥 Replacing the Descripted and Choices type hint with a composition based system

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#227]
I'm worried about the expandability of our current system for choosing application command arg types. Right now there is only `Descripted` and `Choices` for type hints but will have to add `ChannelTypes`, `MinValue`, `MaxValue`, `AutoComplete` and possibly `Name`. A system using recursion would be fine with the current system but it won't be readable so I think we should use composition.
```python
@command
def command(
    recursion: Descripted[AutoComplete[MinValue[MaxValue[int, 10], 0], 5], "Something"]
    composition: CommandArg[int, Description["something"], MinValue[0], MaxValue[10], AutoComplete[5]]
):
    pass
```

**Comment by Endercheif** [comment]
I really like this idea. Composition makes it much easier to read.

**Comment by Sigmanificient** [comment]
indeed
