### ISSUE TITLE
:bug: API Methods on `HTTPClient` have data param as required

### ISSUE THREAD

**Issue by Endercheif** [Pincer-org/Pincer#233]
**Describe the bug**
On the `HTTPClient` class, the methods that have a data parameter, have it as a required argument. This causes issues with routes that do not supply the data param.

**Expected behavior**
I should be able to do something such as `http.put("some/route/here")` and it will allow the missing data argument.

**Comment by Lunarmagpie** [comment]
https://github.com/Pincer-org/Pincer/blob/main/pincer/core/http.py#L411
Data is already optional?

**Comment by Endercheif** [comment]
I see. I think I know what went wrong for me. I was working on a implementing #222 but I was using an old version of pincer when doing so. Closing this. Thanks for that
