### ISSUE TITLE
:building_construction: Gateway URL should be gotten dynamically

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#254]
> [The first step in establishing connectivity to the gateway is requesting a valid websocket endpoint from the API. This can be done through either the Get Gateway or the Get Gateway Bot endpoint.](https://discord.com/developers/docs/topics/gateway#connecting-to-the-gateway)

`GatewayConfig`'s `socket_base_url` parameter should probably be removed when the change is made.

**Comment by shivamdurgbuns** [comment]
@Lunarmagpie  Can you please elaborate more on what is being required here.

**Comment by Lunarmagpie** [comment]
@shivamdurgbuns ofc
In the folder `pincer/_config` there's the `GatewayConfig` class. There's a parameter called `socket_base_url` as I mentioned before. This is static but it should be dynamic. (The parameter should be removed imo since `uri()`'s dependence on it should be removed.`)
In the `pincer.core.gateway.Dispatcher` class, `GatewayConfig`'s `uri()` function Is used to create a websocket connection with discord. The base url that you get from the discord API endpoints in the original post should be used there.
Also some notes: The method that you do should store all the information from the endpoint so we can use it later for sharding. You can also use `async with` with the `pincer.core.http.HTTPClient` class and that might help.
I hope that helps! Ask more questions if you have them.
