### ISSUE TITLE
:sparkles: API For interacting with Message Components

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#255]
Mostly opening this issue so I can get it in the todo list. I don't have a very good idea of what the API would be but It will probably use `Client.wait_for`/`Client.loop_for` so keep those in mind.

**Comment by Lunarmagpie** [comment]
I've been thinking about an API like this
```python

@command
async def some_command(self, ...):
    return a button with id "1234"

@button("1234")
async def on_button_pressed(self, interaction, ...)
    pass
```
It looks a little bloated but I thought about it and if people do one command per cog it will be super easy to read since the indentation is low.

**Comment by Lunarmagpie** [comment]
Ill likely do this at some point but a lot more has to be changed than I expected so I'm doing a few smaller things first

**Comment by Endercheif** [comment]
Currently I am working on modifying `convert_message` to allow a list of things. With that, multiple message components can be returned and things can be mixed returned.

My suggestion after that is pretty much the same as yours.
```py
@command
async def some_command(self, ctx):
    return "These are some buttons", help_button, other_button # tuple[str, Button, Button]

@button(id=1234, label="press me") # the decorator turns this into a button object
async def help_button(self, interaction) -> None:
# can respond to interaction here
    ...
    
@button(id=1235, label="cool")
async def other_button(self, interaction) -> None:
    ...
```

**Comment by Lunarmagpie** [comment]
That's a really good idea. It looks like it'll be a really good way to use message components if you dont need dynamic select menu options.

**Comment by Lunarmagpie** [comment]
i forgor :skull: to close this
