### ISSUE TITLE
✨ Adding cli for easier project start

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#260]
The goal is to add a small CLI that will generate a project base from a template.

> The following templates will be available:
```
minimal   a single bot.py file
small     bot.py + cogs folder (1 demo cog)
full      python package (previous + dir + setup + ...)
```

Usage example:
```sh
pincer "my bot" full
```

other commands
```
pincer -v                       show pincer version
pincer about                    more about the lib
pincer docs/help                open docs.pincer.dev
```
maybe more in the  future?

**Comment by Lunarmagpie** [comment]
There should be a `pincer run`/`pincer start` command so we're a full on framework lol
