### ISSUE TITLE
:sparkles: Support for Sharding

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#263]
https://discord.com/developers/docs/topics/gateway#sharding
https://discord.com/developers/docs/topics/gateway#sharding-for-very-large-bots

**Comment by RPSMain** [comment]
So weird thing to suggest but maybe bots should Be automatically sharded? It shouldn't hurt anyone to have it on automatically

**Comment by Lunarmagpie** [comment]
pretty sure thats how dpy does it. I don't really have a preference tbh.

**Comment by RPSMain** [comment]
> pretty sure thats how dpy does it. I don't really have a preference tbh.

no? i mean like automatically activated by the lib not needing to enable it

**Comment by Lunarmagpie** [comment]
Not sure but my gut is that it'll abstract away too much

**Comment by RPSMain** [comment]
wdym?

**Comment by Lunarmagpie** [comment]
I think its assumed that bots won't be sharded by default and we shouldn't do whats more unexpected.
