### ISSUE TITLE
:sparkles: Implement Every Single Endpoint

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#265]
[I've compiled a spreadsheet with every endpoint](https://docs.google.com/spreadsheets/d/15PWgbo8HNStsMbBpvJVmagIyUfWkZaIZksRS108GcS4/edit?usp=sharing)
If I missed one please tell me. If you want to implement any of these please claim the ones you want in the comments and you can ask me for edit access on discord if you want.

**Comment by Sigmanificient** [comment]
wah your are insane

**Comment by trag1c** [comment]
you're great, thanks for creating this :pray:

**Comment by Endercheif** [comment]
I'll take all the sticker related ones (`B32:B38`)

**Comment by Lunarmagpie** [comment]
You won't be able to do Create Guild Sticker yet because File is missing some functions.

**Comment by Lunarmagpie** [comment]
It is not possible to upload files to discord with the FIle object. DM me for more info on using it. (or grep the code ig lol)

**Comment by Endercheif** [comment]
I'll take all the User ones (`K3:K11`)

**Comment by Endercheif** [comment]
E6 
#315
