### ISSUE TITLE
✨ Provide grep'able character/ flag to debug log to disable sensitive information for bug reports.

### ISSUE THREAD

**Issue by FCLC** [Pincer-org/Pincer#296]
It's mentioned in [README.md](https://github.com/Pincer-org/Pincer#readme) that extended/debug logging can expose sensitive data. Preempting the eventual need for sharing bug reports with the pincer dev team, I'd like to both request and then suggest the following:

I'd request that a flag be added to the debug log to disable sensitive information from being written to logs for the sake of data protection/safety. Alternatively produce matched logs with one containing sensitive data, the other without. 

Quick suggestion for Linux (be they GNU, alpine or other), and BSD installs:

If the implementation above is deemed too difficult to implement at this stage, possibly add the phrase 
[shareable] in front of any debug lines that are not sensitive. 
That way a simple 
```cat "foo.log" | grep [shareable] >> "bar.log"```
would produce a shareable debug log minus sensitive data, without creating much if any code debt, relying on sys libs and programs guaranteed to have a stable posix interface (cat, grep and the "|" piping mechanism )

The above would strip any and all lines that would have contained sensitive data from ```foo.log``` and is a simple mechanism for implementing different logging levels.

**Comment by Lunarmagpie** [comment]
Anyone know if we actually are logging anything sensitive rn or if that's old and needs to be updated?

**Comment by Sigmanificient** [comment]
I believe anything that is shown within the logs are safe if the logs are from a closed connection and not an active bot, as the key explicitly shown are regenerated for every different connection. The token is already shorten
```
DEBUG:websockets.client:> TEXT '{"op": 2, "d": {"token": "ODkxNzM4NTExMzExNTE1N..., "s": null, "t": null}' [227 bytes]
```

**Comment by trag1c** [comment]
> The token is already shorten
> 
> ```
> DEBUG:websockets.client:> TEXT '{"op": 2, "d": {"token": "ODkxNzM4NTExMzExNTE1N..., "s": null, "t": null}' [227 bytes]
> ```
> 
> and i dont think `21/51` char make it anywhere near from being guessable.

Worth mentioning that the first part of a bot token is its user ID, which is something pretty public, especially if we share a server with the bot

**Comment by Lunarmagpie** [comment]
I think the best thing to do here is update our readme since it seems pretty outdated.

**Comment by Lunarmagpie** [comment]
The updated readme has been merged
