### ISSUE TITLE
♻️ Moving cached objects to a cache object

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#334]
For example
```
# current
Client.guilds
# With cache
Client.cache.guilds
```

Hikari and Serenity do this. I think it's a much better decision over all since I think it'll simplify storing voice states once we get to that.

**Comment by Endercheif** [comment]
I currently am working on this

**Comment by Endercheif** [comment]
Instead of just a dictionary, I'm using a custom object which wraps around a deque mainly so I can have a max length and automatically remove the oldest item.

**Comment by Lunarmagpie** [comment]
🚀 🚀 🚀

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
