### ISSUE TITLE
:sparkles: Timed rate limiting for HTTP and Gateway

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#338]
https://discord.com/developers/docs/topics/gateway#rate-limiting
Gateway has to be rate limited to 120 gateway commands every 60 seconds

https://discord.com/developers/docs/topics/rate-limits#global-rate-limit
HTTP API has a global rate limit. It looks like its 50 by default and can be increased.

I have no idea how to approach this problem so i probably won't do this one

**Comment by Arthurdw** [comment]
We could use the existing `SlidingWindow` *(in utils)* class and make a static instance of it. Then we can check on this instance if the request/gateway command is allowed.

**Comment by Lunarmagpie** [comment]
Sliding window won't work. It needs to wait until not rate limited then send a request. Similar to how HTTP user rate limits are implemented.
