### ISSUE TITLE
:bug: Fix zlib-stream compression for the Gateway

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#357]
When using `zlib-stream` compression, the bot can crash with an error like `invalid block lengths`. I found that stopping and starting the bot really quickly in succession is an easy way to recreate the error. I think it can also happen after the bot is running for a while though.

Everything that needs to be changed should be contained to `pincer.core.Gateway`. `__buffer` already exists to store the buffer. There is only one global inflator though, I have no idea if each shard needs one.

`GatewayConfig` should be imported and do `GatewayConfig.compression = "zlib-stream"` to change the compression type while testing.

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
