### ISSUE TITLE
:bug: Switch CommandArg to use Annotated so it is complient with python typing

### ISSUE THREAD

**Issue by Lunarmagpie** [Pincer-org/Pincer#370]
https://docs.python.org/3/library/typing.html#typing.Annotated
Also the rest of the types will need some slight changing

**Comment by Endercheif** [comment]
@Lunarmagpie I am closing this as it is for Python >=3.9 and Pincer supports 3.8.

**Comment by Lunarmagpie** [comment]
Annotated is available through typing extensions in 3.8. The implementation I ended up with doesn't even import it (python jank) so there shouldn't be any issues.
