### ISSUE TITLE
:bug: Workflow "sort-all" fail when nothing to commit

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#375]
### Describe the bug

Since sort-all is active on all branch, it now fail on pr if there is nothing to sort

### Relevant console output

see [here](https://github.com/Pincer-org/Pincer/runs/4761952669?check_suite_focus=true)

**Comment by Lunarmagpie** [comment]
I'm pretty sure this works now

**Comment by Sigmanificient** [comment]
yeah
