### ISSUE TITLE
Error handling on message delete

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#411]
### Is your feature request related to a problem? Please describe.

``message.delete`` doesn't appear to do any error handling.

### Describe the solution you would like

``message.delete`` does error handling.

### Describe alternatives you have considered

Ignoring issues. Works fine for my project, however likely wouldn't be advisable for others.

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
