### ISSUE TITLE
``UserMessage.from_id`` types are playing up

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#412]
### Describe the bug

When attempting to pass the id's for both the message id and channel id, I receive the following type inference issue.

``Expected type 'Snowflake', got 'int' instead ``

I'd love to *not* get this issue.

### Steps to Reproduce

```markdown
``UserMessage.from_id(client, 12345, 6789)``
```

### Pincer Version used

0.15.3

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
