### ISSUE TITLE
Add a way to see if a UserMessage is a system message

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#415]
### Is your feature request related to a problem? Please describe.

Currently, I need to dive down into type enums and run checks myself. This is not ideal for an end user

### Describe the solution you would like

Property on the message for it. Heres how discord.py implements it for reference
```pyython
    def is_system(self) -> bool:
        """:class:`bool`: Whether the message is a system message.

        A system message is a message that is constructed entirely by the Discord API
        in response to something.

        .. versionadded:: 1.3
        """
        return self.type not in (
            MessageType.default,
            MessageType.reply,
            MessageType.application_command,
            MessageType.thread_starter_message,
        )
```

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
