### ISSUE TITLE
Aggregate message mentions

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#416]
### Is your feature request related to a problem? Please describe.

I have a suitable usecase for needing *all* mentions in a message, however, they are currently split out into three attributes.

I prose one of two things:
a) Rename ``message.mentions`` to ``message.mention_users`` to reduce confusion

b) Do the above, and point ``message.mentions`` as a cached property which aggregates all 3

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
