### ISSUE TITLE
:bug: GuildMember.permissions does not take account of owner

### ISSUE THREAD

**Issue by Kylianalex** [Pincer-org/Pincer#418]
### Describe the bug

GuildMember.permissions should return all permissions if the member is the owner 

### Steps to Reproduce

```markdown
1. add a `return ctx.author.permissions` in a command
2. if the member doesn't have any role, it will return 0
```

### Relevant console output

 `0`

### Pincer Version used

git

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
