### ISSUE TITLE
``Client(intents=..)`` is typed wrong (maybe)

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#423]
### Describe the bug

The following code will throw ``Expected type 'Optional[Intents]', got 'int' instead``
```python
intents = Intents.all()
b = Client(file["token"], intents=intents)
```

### Steps to Reproduce

```markdown
intents = Intents.all()
b = Client(file["token"], intents=intents)
```

### Pincer Version used

0.15.3

**Comment by ooliver1** [comment]
This seems to have been fixed, the type is `Intents` in `Client` and pyright is happy.
