### ISSUE TITLE
:bug: ``UserMessage.type`` is missing

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#424]
### Describe the bug

When using ``UserMessage`` form ``on_message``, ``msg.type is MISSING``

### Pincer Version used

0.15.3

**Comment by Skelmis** [comment]
#415

**Comment by Skelmis** [comment]
This relates to ``from_dict`` not setting the type correctly.

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
