### ISSUE TITLE
:bug: commands parameters are always str

### ISSUE THREAD

**Issue by Kylianalex** [Pincer-org/Pincer#425]
### Describe the bug

example:
adding a Role, int or Channel parameter to a command get a ``str`` object

### Steps to Reproduce

```markdown
1. create a command with a any parameter
2. print type(param)
```

### Pincer Version used

git

**Comment by Kylianalex** [comment]
fixed, going to pull

**Comment by Arthurdw** [comment]
Closed due to depreciation, thank you for your effort ♥
