### ISSUE TITLE
Timeout support

### ISSUE THREAD

**Issue by Skelmis** [Pincer-org/Pincer#430]
### Is your feature request related to a problem? Please describe.

I have a use case where I wish to timeout members. Currently, I can't, I just have to error and say that hey timeouts are not supported.

### Describe the solution you would like

Timeouts in Pincer

**Comment by Arthurdw** [comment]
Hey there, sorry for the late response.  
  
I'm not sure what you mean by timeouts? I can't seem to find this in the discord documentation either _(besides from AFK timeouts)._  
  
Could you explain your enhancement a bit more?

**Comment by ooliver1** [comment]
This *should* have been closed by #324
