### ISSUE TITLE
:bug: Having loads of pre-registered `ApplicationCommands` causes you to be ratelimited `on_ready`

### ISSUE THREAD

**Issue by TheUntraceable** [Pincer-org/Pincer#454]
### Describe the bug

So I have my Discord Bot which was created with another library, and it has loads of Slash Commands, and I noticed when testing out Pincer that I consistently kept on getting ratelimited. This was confusing me, but after checking the logs, you've been calling an individual DELETE on the SlashCommand `application/APPLICATION_ID/commands/COMMAND_ID`. As there were loads of `ApplicationCommand`s registered, there starts to gather a rather large list of requests.

### Steps to Reproduce

```markdown
Create several `ApplicationCommand`'s.
Run a Discord Bot with Pincer.
```

### Relevant console output

RateLimitError: Too Many Requests. The scope is user. Retrying in 19.895 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.89 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.888 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.891 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.885 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.89 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.886 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.886 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.882 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.88 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.882 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.874 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.855 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.851 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.852 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.851 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.851 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.849 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.848 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.847 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.849 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.847 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.848 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.845 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.847 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.845 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.846 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.846 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.874 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.844 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.847 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.844 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.843 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.841 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.838 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.84 seconds
RateLimitError: Too Many Requests. The scope is global. Retrying in 0.313 seconds
RateLimitError: Too Many Requests. The scope is global. Retrying in 0.309 seconds
RateLimitError: Too Many Requests. The scope is global. Retrying in 0.306 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.823 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.842 seconds
RateLimitError: Too Many Requests. The scope is global. Retrying in 0.296 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.333 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.331 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.319 seconds
RateLimitError: Too Many Requests. The scope is user. Retrying in 19.32 seconds

### Pincer Version used

0.16.0

**Comment by Arthurdw** [comment]
Fix would be to add a parameter for initialization. Which then uses the bulk commands instead of separate.

We could make this the default, and make thr current one a opt in.
