### ISSUE TITLE
Middlewares current import is changing the cwd

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#76]
**Describe the bug**
When using `@client.event`, the  current working directory is changed to  `Lib/pincer/middlewares` as the `chdir` is used within the `__init__.py` of `middlewares`.

**To Reproduce**

```py
import os
from pincer import Client


class Bot(Client):

    def __init__(self):
        super().__init__(token='')


print(os.getcwd())
```

> `D:\Pincer\pincer\middleware`

**Expected behavior**
> `D:\Pincer\dev`

**Desktop (please complete the following information):**
> __os__: `windows`
__python__: `3.9.6`
__pincer__: `0.6.10`

**Comment by Endercheif** [comment]
Issue from `Pincer/pincer/middleware/__init__.py` line 19

**Comment by Sigmanificient** [comment]
> 
> 
> Issue from `Pincer/pincer/middleware/__init__.py` line 19

indeed, might use a context manager for this

**Comment by Arthurdw** [comment]
Issue got resolved in [this commit](https://github.com/Pincer-org/Pincer/commit/11c113469352237f465e83ec46a581953693b364)
