### ISSUE TITLE
✨ Middleware implementation

### ISSUE THREAD

**Issue by Arthurdw** [Pincer-org/Pincer#82]
Most middleware still has to be implemented.

Some files are already present in `pincer.middleware`.

Find the events [here](https://github.com/Pincer-org/Pincer/issues/82#issuecomment-946309951)

**Comment by yashpy** [comment]
Please assign me this work.

**Comment by Sigmanificient** [comment]
> sure!

**Comment by krishnajalan** [comment]
hello, I want to pick up this issue.

**Comment by Arthurdw** [comment]
> 
> 
> hello, I want to pick up this issue.

Sure :D

**Comment by Arthurdw** [comment]
Not all middleware has been implemented yet :)
Thanks @krishnajalan for your contributions tho ♥

**Comment by Endercheif** [comment]
If anyone wants to finish this. here are the middlewares that have not been implemented or do not have an export method.
(list from logs)

- [activity_join.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/activity_join.py)
- [activity_join_request.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/activity_join_request.py)
- [activity_spectate.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/activity_spectate.py)
- [channel_create.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/channel_create.py)
- [error.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/error.py)
- [guild_status.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/guild_status.py)
- [notification_create.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/notification_create.py)
- [speaking_start.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/speaking_start.py)
- [speaking_stop.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/speaking_stop.py)
- [voice_channel_select.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/voice_channel_select.py)
- [voice_connection_status.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/voice_connection_status.py)
- [voice_settings_update.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/voice_settings_update.py)
- [voice_state_create.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/voice_state_create.py)
- [voice_state_delete.py](https://github.com/Pincer-org/Pincer/tree/main/pincer/middleware/voice_state_delete.py)

**Comment by Endercheif** [comment]
Looking through the discord api docs, other that the ones listed above, there are still some left to implement. @Arthurdw linked to the RPC events when we should be checking the [gateway events](https://discord.com/developers/docs/topics/gateway#commands-and-events).  This issue can be split up between multiple people.
Here are the events not yet added:


- [Channel Update](https://discord.com/developers/docs/topics/gateway#channel-update)
- [Channel Delete](https://discord.com/developers/docs/topics/gateway#channel-delete)
- [Channel Pins Update](https://discord.com/developers/docs/topics/gateway#channel-pins-update)
- [Thread Create](https://discord.com/developers/docs/topics/gateway#thread-create)
- [Thread Update](https://discord.com/developers/docs/topics/gateway#thread-update)
- [Thread Delete](https://discord.com/developers/docs/topics/gateway#thread-delete)
- [Thread List Sync](https://discord.com/developers/docs/topics/gateway#thread-list-sync)
- [Thread Member Update](https://discord.com/developers/docs/topics/gateway#thread-member-update)
- [Thread Members Update](https://discord.com/developers/docs/topics/gateway#thread-members-update)
- [Guild Update](https://discord.com/developers/docs/topics/gateway#guild-update)
- [Guild Delete](https://discord.com/developers/docs/topics/gateway#guild-delete)
- [Guild Ban Add](https://discord.com/developers/docs/topics/gateway#guild-ban-add)
- [Guild Ban Remove](https://discord.com/developers/docs/topics/gateway#guild-ban-remove)
- [Guild Emojis Update](https://discord.com/developers/docs/topics/gateway#guild-emojis-update)
- [Guild Stickers Update](https://discord.com/developers/docs/topics/gateway#guild-stickers-update)
- [Guild Integrations Update](https://discord.com/developers/docs/topics/gateway#guild-integrations-update)
- [Guild Member Add](https://discord.com/developers/docs/topics/gateway#guild-member-add)
- [Guild Member Remove](https://discord.com/developers/docs/topics/gateway#guild-member-remove)
- [Guild Member Update](https://discord.com/developers/docs/topics/gateway#guild-member-update)
- [Guild Members Chunk](https://discord.com/developers/docs/topics/gateway#guild-members-chunk)
- [Guild Role Create](https://discord.com/developers/docs/topics/gateway#guild-role-create)
- [Guild Role Update](https://discord.com/developers/docs/topics/gateway#guild-role-update)
- [Guild Role Delete](https://discord.com/developers/docs/topics/gateway#guild-role-delete)
- [Integration Create](https://discord.com/developers/docs/topics/gateway#integration-create)
- [Integration Update](https://discord.com/developers/docs/topics/gateway#integration-update)
- [Integration Delete](https://discord.com/developers/docs/topics/gateway#integration-delete)
- [Invite Create](https://discord.com/developers/docs/topics/gateway#invite-create)
- [Invite Delete](https://discord.com/developers/docs/topics/gateway#invite-delete)
- [Message Delete Bulk](https://discord.com/developers/docs/topics/gateway#message-delete-bulk)
- [Message Reaction Add](https://discord.com/developers/docs/topics/gateway#message-reaction-add)
- [Message Reaction Remove](https://discord.com/developers/docs/topics/gateway#message-reaction-remove)
- [Message Reaction Remove All](https://discord.com/developers/docs/topics/gateway#message-reaction-remove-all)
- [Message Reaction Remove Emoji](https://discord.com/developers/docs/topics/gateway#message-reaction-remove-emoji)
- [Presence Update](https://discord.com/developers/docs/topics/gateway#presence-update)
- [Stage Instance Create](https://discord.com/developers/docs/topics/gateway#stage-instance-create)
- [Stage Instance Delete](https://discord.com/developers/docs/topics/gateway#stage-instance-delete)
- [Stage Instance Update](https://discord.com/developers/docs/topics/gateway#stage-instance-update)
- [Typing Start](https://discord.com/developers/docs/topics/gateway#typing-start)
- [User Update](https://discord.com/developers/docs/topics/gateway#user-update)
- [Voice State Update](https://discord.com/developers/docs/topics/gateway#voice-state-update)
- [Voice Server Update](https://discord.com/developers/docs/topics/gateway#voice-server-update)
- [Webhooks Update](https://discord.com/developers/docs/topics/gateway#webhooks-update)

**Comment by Endercheif** [comment]
I can work on some of these too. I will start with Channel Update, Channel Delete, Channel Pins Update. Feel free to take some of the other ones.

**Comment by beastmatser** [comment]
I added the last middleware, the code is on a pull request for the branch in #163 , so @Endercheif if you could merge it, so that it can be reviewed that would be awesome :)

**Comment by Endercheif** [comment]
Updating this list right now for the things that @beastmatser added in #174

**Comment by beastmatser** [comment]
`Guild Integrations Update` and `Webhooks Update` are now also added in #174

**Comment by Endercheif** [comment]
This has been finished. Just waiting on #163 and #174 to be merged.
