### ISSUE TITLE
✨Type checking imports for all type hints

### ISSUE THREAD

**Issue by Arthurdw** [Pincer-org/Pincer#83]
## Task

Only import type hints when `TYPE_CHECKING` is true.

Must be present:
```py
from __future__ import annotations

from typing import TYPE_CHECKING
```

## Example

```py
from __future__ import annotations

from typing import TYPE_CHECKING
from dataclasses import dataclass


if TYPE_CHECKING:
    from typing import List


@dataclass
class Foo:
    bar: List[int] = None
```

**Comment by Sigmanificient** [comment]
Has been started in this [commit](https://github.com/Pincer-org/Pincer/commit/b6310719b0bd846cfd1ae2902ccc9f1fde2da96a)

**Comment by biswain2309** [comment]
Would you mind if I take this issue up?

**Comment by Sigmanificient** [comment]
> Would you mind if I take this issue up?

Sure, go ahead! We are opening issues in order to give people idea for pull requests for the Hacktoberfeast

**Comment by biswain2309** [comment]
Could you please assign this issue to me, so that I can start working on it?

**Comment by ooliver1** [comment]
pf well issue is sphinx cannot detect types with this

**Comment by mjneff2** [comment]
Sure, can I get this assigned.

**Comment by ooliver1** [comment]
Autodoc_typehints hasn't even worked properly so I'll get all typehint imports in there like it should
