### ISSUE TITLE
📝 Document code further

### ISSUE THREAD

**Issue by Arthurdw** [Pincer-org/Pincer#86]
Further document docstrings &/or create documentation where none is present but is needed.

**Comment by Sly-Little-Fox** [comment]
~~Arthur opening issues for **everything**~~

**Comment by Sriram-bb63** [comment]
I would like to work on this issue

**Comment by nayan2306** [comment]
I would like to work on this issue

**Comment by nayan2306** [comment]
@Sigmanificient can you berif once what we need to do?

**Comment by nayan2306** [comment]
I have little bit confusion

**Comment by Sigmanificient** [comment]
For this issue, it's about all the missing docstring within the library and improving the general documentation. 
Not the funniest one, i know, but we really need it. 

Optimally, Having docstring everywhere, but at least having the most important up filled up.
We are using reStructureText as the docstring format so it might follow this 
```py
"""
General description of the method/function/class.

:param foo
   description of the param (attribute, if class)

(if needed)
:return type:
  what the method/function return

(if needed)
:throw Exception:
  The kind of exception that may occurs when using this method/funcion
"""
```

**Comment by ooliver1** [comment]
Well I have a bit of previous experience with rtdio and Sphinx

I started working on it half an hour ago and have now fixed the build errors, I will continue tomorrow and PR my changes at the end of the day. I may work on it again when I have time during school but I'll take up on this as a 'fun' thing to do to get better at Sphinx

**Comment by Sigmanificient** [comment]
There is absolutely no problem, take your time!
Haha, i dont really like sphinx configuration tbh, so thanks for you dedication!

**Comment by Sriram-bb63** [comment]
I will unassign myself because my PR has been merged :v:
