### ISSUE TITLE
✨ Support for `tasks.loop`

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#87]
## Task
Make a decorator that transform a asynchronous function to a task object. 

```py
@task.loop(minute=30)
async def my_task(self):
    ...
```

When calling `my_task.start()` this will register the task to repeat the given amount of time.

**Comment by mwath** [comment]
It sounds very useful!
I would love to contribute to this project starting with this issue if you don't mind.

**Comment by Arthurdw** [comment]
> It sounds very useful! I would love to contribute to this project starting with this issue if you don't mind.

We don't mind, all contributions are welcome! 👐
