### ISSUE TITLE
✨ Implement all command argument types

### ISSUE THREAD

**Issue by Arthurdw** [Pincer-org/Pincer#89]
Implement all `AppCommandOptionType`s

This means for example that a user can be an argument, and also means that a user object gets provided to the command call.

**Comment by Lunarmagpie** [comment]
For the next person to look at this:
Handling for Mentionable, Subcommand, & Subcommand Group are left.

**Comment by mwath** [comment]
Isn't `Mentionable` as simple as `Union[User, Role]` ?
From the docs: ["Includes users and roles"](https://discord.com/developers/docs/interactions/application-commands#application-command-object)

**Comment by Arthurdw** [comment]
> 
> 
> Isn't `Mentionable` as simple as `Union[User, Role]` ? From the docs: ["Includes users and roles"](https://discord.com/developers/docs/interactions/application-commands#application-command-object)

Oh daimn. I didn't even know that was a discord type.
Well yes and no then, because we will be using Union for subcommand options.

**Comment by mjneff2** [comment]
Will try some work on this.

**Comment by Lunarmagpie** [comment]
FINALLY CLOSED
that took a long time
