### ISSUE TITLE
✨ Implement channel editing

### ISSUE THREAD

**Issue by Sigmanificient** [Pincer-org/Pincer#93]
## Task

Implemented a `channel.edit` method. In this method you can pass named arguments for the channel attribute(s) that have to change.

#### Example:
```py
@command()
async def update_channel():
    channel = await Channel.from_id(...)
    
    # the method to add
    await channel.edit(name="foo")

```

**Comment by Endercheif** [comment]
I can take this

**Comment by Sigmanificient** [comment]
> 
> 
> I can take this

sure!
